project:
  type: website

website:
  title: "Anna L. Ziff"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - research.qmd
      - teaching.qmd

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

