---
title: "Research"
---

# Working Papers


<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5182368" target="_blank">
  <strong>Beyond the Local Impacts of Place-Based Policies: Spillovers through Latent Housing Markets</strong>
</a>


<details>
<summary>Abstract</summary>
Place-based policies target geographic areas, aiming to generate localized investment for economic development. Do place-based policies create new economic activity or do they reallocate it? Empirically evaluating this question is challenging because of the difficulty in ascertaining areas that might experience spillovers. I develop a data-driven approach to characterize the areas most likely to be affected when others receive targeted investment. Tax Increment Financing in Chicago provides a setting to consider whether place-based policies revitalizing neighborhoods are zero-sum. I find that while the effect of Tax Increment Financing on property values in targeted areas is positive, the spillover effect on property values in non-targeted areas is negative. Business activity shifts in a manner consistent with Tax Increment Financing subsidizing development that would have occurred elsewhere. I combine the direct and spillover effects to calculate a back-of-the-envelope estimate of an overall effect close to zero. Due to the targeting of the policy, it results in a limited amount of redistribution towards relatively disadvantaged targeted areas.
</details>

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5236211" target="_blank">
  <strong>Levees and the Crowd-Out of Flood Insurance Demand</strong>
</a> (with Mythili Vinnakota)

<details>
<summary>Abstract</summary>

Public investments in disaster mitigation may crowd out demand for insurance. We measure the extent of substitution between flood-mitigating infrastructure and public flood insurance. Using a novel dataset of U.S. levee provision, we find that levee construction lowers flood risk and reduces insurance take-up by 61%, removing \$300 million in coverage. Levee accreditation, which reduces premiums and lifts mandatory purchase requirements, offsets part of this decline, recovering \$160 million in coverage. The positive effect of accreditation indicates that reducing premiums increases insurance take-up, despite the counteracting influence of mandate removal.
</details>

# Works in Progress

**Rental Choice Sets in Low- and High-Opportunity Neighborhoods for Housing Choice Voucher Program Participants** (with JoonYup Park)


# Publications

<a href="https://www.journals.uchicago.edu/doi/abs/10.1086/732668?casa_token=XbRK0DC1zZIAAAAA%3A3C0MtSj0oxT8AwZ4A7Wc20gF5Qz93uo98hLbtMhqvdQ15JQXyigb8vaKeHGSCMHwTxvog8xwInPy&casa_token=cZHFnPH7lEgAAAAA%3AjUynL4ZeNNfRysHkH0a2qqdx8-HyMJtUTleb1XitRK5CEegxS421WGBBKrL4jxqUXNPSc0SIUCFi&journalCode=jole" target="_blank">
  <strong>Association between the Volatility of Income and Life Expectancy in the U.S.</strong>
</a> (with V. Joseph Hotz and Emily E. Wiemers). *Journal of Labor Economics*, 43(Supp 1):S153–S178, 2025.

<details>
<summary>Abstract</summary>
We examine the relationship between income volatility and life expectancy in mid-sized US commuting zones between 2006 and 2014. We use a commercial dataset, InfoUSA, to measure income volatility, which we link to estimates of life expectancy by gender, county, race, and income. We find that higher income volatility in a county is associated with lower life expectancy but only at the bottom of the income distribution and primarily for non-Hispanic Whites. Though we cannot extrapolate our findings to individual-level relationships, we do link them to existing literatures on place-based differences in mortality and the relationship between volatility and health.
</details>

<a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/imhj.21759?casa_token=8ymuZDzhZjEAAAAA%3AyZ9dfYvaEJ7WJ9uGnoEd96sbjQ3d9Z7tIBpLLRxF7qrRx-mzx-M-gy7MvJSvj90hgDP8T-jOVazCt1g" target="_blank">
<strong>Early Childhood Education and Crime</strong>
</a> (with Jorge Luis García and James J. Heckman). *Infant Mental Health Journal*, 40(1):141–151, 2019.

<details>
<summary>Abstract</summary>
This article presents new evidence on the crime-reducing impacts of a high-quality, intensive early childhood program with long-term follow-up, evaluated by a randomized controlled trial. Proportionately, more women than men decrease their criminal activity after participating in the program. This gender difference arises because of the worse home environments for girls, with corresponding greater scope for improvement by the program. For both genders, treatment effects are larger for the least-advantaged children, as measured by their mother's education at baseline. The dollar value of the social cost of criminal activity averted is higher for men because they commit more costly violent crimes.
</details>

<a href="https://www.sciencedirect.com/science/article/abs/pii/S0014292118300953?via%3Dihub" target="_blank">
  <strong> Gender Differences in the Benefits of an Influential Early Childhood Program </strong>
</a> (with Jorge Luis García and James J. Heckman). *European Economic Review*, 109:9–22, 2018

<details>
<summary>Abstract</summary>
This paper studies the life-cycle impacts of a widely emulated high-quality, intensive early childhood program with long-term follow up. The program starts early in life (at 8 weeks of age) and is evaluated by an RCT. There are multiple treatment effects which we summarize through interpretable aggregates. Girls have a greater number of statistically significant treatment effects than boys and effect sizes for them are generally bigger. The source of this difference is worse home environments for girls with greater scope for improvement by the program. Fathers of sons support their families more than fathers of daughters.
</details>

<a href="https://www.sciencedirect.com/science/article/pii/S1090944317301643?casa_token=oDPqRsBrVT8AAAAA:plbBgHkvJqUS_52cno3CZLwmNj6clTgGyVrzWSaETHaR7Uz_A9oddJJNb7IjfYVjBIUldeP6zPU" target="_blank">
<strong>Evaluation of the Reggio Approach to Early Education</strong> 
</a> (with Pietro Biroli, Daniela Del Boca, James J. Heckman, Lynne Pettler Heckman, Yu Kyung Koh, Sylvi Kuperman, Sidharth Moktan, Chiara D. Pronzato, Anna L. Ziff). *Research in Economics*, 72(1):1–32, March 2018.

<details>
<summary>Abstract</summary>
We evaluate the Reggio Approach using non-experimental data on individuals from the cities of Reggio Emilia, Parma and Padova belonging to one of five age cohorts: ages 50, 40, 30, 18, and 6 as of 2012. The treated were exposed to municipally offered infant-toddler (ages 0–3) and preschool (ages 3–6) programs in Reggio Emilia. The control group either did not receive formal childcare or were exposed to programs offered by municipal systems (outside of Reggio Emilia), or by state or religious systems (in all three cities). We exploit the city-cohort structure of the data to estimate treatment effects using three strategies: difference-in-differences, matching, and matched-difference-in-differences. Most positive and significant effects are generated from comparisons of the treated with individuals who did not receive formal childcare. Relative to not receiving formal care, the Reggio Approach significantly boosts outcomes related to employment, socio-emotional skills, high school graduation, participation in elections, and obesity. Comparisons with individuals exposed to alternative forms of childcare do not yield strong patterns of positive and significant effects. This suggests that differences between the Reggio Approach and other alternatives are not sufficiently large to result in significant differences in outcomes. This interpretation is supported by a survey we conduct, which documents increasing similarities in the administrative and pedagogical practices of childcare systems in the three cities over time.
</details>